SCALE_OPTIONS = [round(i / 10, 1) for i in range(1, 21)]
TRANSPARENCY_OPTIONS = [round(i / 10, 1) for i in range(1, 11)]
DEFAULT_SCALE_INDEX = 9
DEFAULT_TRANSPARENCY_INDEX = 9

MOVE_INTERVAL = 30
JITTER_INTERVAL = 5
SPEED_X = 3.0
SPEED_Y = 2.0
STOP_CHANCE = 0.003
STOP_DURATION_MIN = 4000
STOP_DURATION_MAX = 8000
RESPAWN_MARGIN = 50
TARGET_CHANGE_MIN = 200
TARGET_CHANGE_MAX = 500
OUTSIDE_TARGET_CHANCE = 0.4
FOLLOW_DISTANCE = 80
FOLLOW_START_DIST = 200
FOLLOW_STOP_DIST = 60
INERTIA_FACTOR = 0.95
INTENT_FACTOR = 0.05
JITTER = 0.15
REST_CHANCE = 0.6
REST_DISTANCE = 20
REST_DURATION_MIN = 1000
REST_DURATION_MAX = 3000
SPEED_WANDER = 0.8
SPEED_FOLLOW = 1.2
SPEED_CURIOUS = 0.5
STAY_PUT_CHANCE = 0.3
PAUSED_ANIMATION_MIN = 30000
PAUSED_ANIMATION_MAX = 120000

MOTION_WANDER = "wander"
MOTION_FOLLOW = "follow"
MOTION_CURIOUS = "curious"
MOTION_REST = "rest"

DISPLAY_ALWAYS_TOP = 1
DISPLAY_HIDE_FULLSCREEN = 2
DISPLAY_DESKTOP_ONLY = 3

GITHUB_RELEASES_URL = "https://github.com/HedgehogBeta/Bue_Toolbox/releases"
GITHUB_RELEASE_API = (
    "https://api.github.com/repos/HedgehogBeta/Bue_Toolbox/releases?per_page=100"
)
UPSTREAM_PROJECT_URL = "https://gitee.com/lzy-buaa-jdi/ameath"
